var pages = [ 

"https://abgcantiksmile.blogspot.com/2019/02/abg-cantik-single-pengen-jadi-artis.html",
"https://abgcantiksmile.blogspot.com/2019/02/awek-comel-calon-menantu-idaman.html",
"https://abgcantiksmile.blogspot.com/2019/02/beautiful-hijaber-manis-masa-kini.html",
"https://abgcantiksmile.blogspot.com/2019/02/bidadari-cantik-elok-rupawan.html",
"https://abgcantiksmile.blogspot.com/2019/02/blkpik.html",
"https://abgcantiksmile.blogspot.com/2019/02/calon-menantu-idaman.html",
"https://abgcantiksmile.blogspot.com/2019/02/cantik-berhijab-jaman-now-kekinian.html",
"https://abgcantiksmile.blogspot.com/2019/02/cantik-cantik-belum-punya-pasangan.html",
"https://abgcantiksmile.blogspot.com/2019/02/dara-cantik-pengayom-masyarakat.html",
"https://abgcantiksmile.blogspot.com/2019/02/gadis-abg-cantik-selfi-bak-bidadari.html",
"https://abgcantiksmile.blogspot.com/2019/02/gadis-kece-cantik-suka-selfi.html",
"https://abgcantiksmile.blogspot.com/2019/02/genit-genit-manja-abis.html",
"https://abgcantiksmile.blogspot.com/2019/02/jilbaber-cantik-nan-baik-hati.html",
"https://abgcantiksmile.blogspot.com/2019/02/jilbaber-cute-cantik-pose-ala-model.html",
"https://abgcantiksmile.blogspot.com/2019/02/kecantikan-alami-gadis-hijaber-unyu-unyu.html",
"https://abgcantiksmile.blogspot.com/2019/02/kecantikan-alami-si-bidadari-desa.html",
"https://abgcantiksmile.blogspot.com/2019/02/penakluk-burung-besi-nan-rupawan.html",
"https://abgcantiksmile.blogspot.com/2019/02/pramugari-cantik-single-cari-jodoh.html",
"https://abgcantiksmile.blogspot.com/2019/02/pretty-muslimah-mencari-jodoh.html",
"https://abgcantiksmile.blogspot.com/2019/02/senyuman-si-cantik-meluluhkan-hati-kaum.html",
"https://abgcantiksmile.blogspot.com/2019/02/suster-cantik-berhijab-single.html",
"https://abgcantiksmile.blogspot.com/2019/03/asian-pretty-girl-single.html",
"https://abgcantiksmile.blogspot.com/2019/03/cute-girly-love-my-friend.html",
"https://abgcantiksmile.blogspot.com/2019/03/pretty-police-women-make-smile.html",
"https://abgcantiksmile.blogspot.com/2019/04/riana-agista-cute-girl.html",
"https://abgcantiksmile.blogspot.com/2019/04/rose-roseanne-park-of-blkpik.html",
"https://abgcantiksmile.blogspot.com/2019/05/beautiful-lovely-girl.html",
"https://abgcantiksmile.blogspot.com/2019/05/happy-girls-feeling-in-love.html",
"https://abgcantiksmile.blogspot.com/2019/06/video-hot-beautiful-girl-making-love.html",
"https://abgcantiksmile.blogspot.com/2020/05/lescala-bikini-top-red-white-fox-swim.html",
"https://abgcantiksmile.blogspot.com/2020/09/beauty-qeens-hot.html",
"https://abgcantiksmile.blogspot.com/2020/09/blog-post.html",
"https://abgcantiksmile.blogspot.com/2020/09/sweety-girl-happy-morning.html",
"https://abgcantiksmile.blogspot.com/2020/09/wmomt.html",
"https://abgcantiksmile.blogspot.com/2020/11/big-boobs.html",
"https://abgcantiksmile.blogspot.com/2020/11/fun-girl.html",
"https://abgcantiksmile.blogspot.com/2020/11/gamer-girl.html",
"https://abgcantiksmile.blogspot.com/2020/11/hot-brunette.html",
"https://abgcantiksmile.blogspot.com/2020/11/pinky-girl.html",
"https://abgcantiksmile.blogspot.com/2020/11/red-girl.html",
"https://abgcantiksmile.blogspot.com/2020/11/sweety-babes.html",
"https://abgcantiksmile.blogspot.com/2020/11/sweety-girls.html",
"https://abgcantiksmile.blogspot.com/2020/11/sweety-sexy-girl.html",
"https://abgcantiksmile.blogspot.com/2020/12/amazing-boobs.html",
"https://abgcantiksmile.blogspot.com/2020/12/omg.html",
"https://abgcantiksmile.blogspot.com/2020/12/on-beach.html",
"https://abgcantiksmile.blogspot.com/2020/12/pinay-girls.html",
"https://abgcantiksmile.blogspot.com/2020/12/red-bikini.html",
"https://abgcantiksmile.blogspot.com/2020/12/scarlet-johansson.html",
"https://abgcantiksmile.blogspot.com/2020/12/selfies-for-blink.html",
"https://abgcantiksmile.blogspot.com/2020/12/smile-girls.html",
"https://abgcantiksmile.blogspot.com/2020/12/super-beautiful-hollywoods-celebrities.html",
"https://abgcantiksmile.blogspot.com/2020/12/super-hot-scarlet-johansson.html",
"https://abgcantiksmile.blogspot.com/2020/12/sweety-babes.html",
"https://abgcantiksmile.blogspot.com/2020/12/sweety-boobs.html",
"https://abgcantiksmile.blogspot.com/2020/12/village-girls.html",
"https://abgcantiksmile.blogspot.com/2020/12/waterfall.html",

];
function randomPage() { 
return pages[Math.round(Math.random() * (pages.length - 1))]; 
} 
location.href= randomPage(); 
